# reconx/report.py
import json
from datetime import datetime

def generate_html(input_file, output_file):
    """
    Generate a simple HTML report from the Nmap scan JSON results.
    """
    with open(input_file, "r") as f:
        data = json.load(f)

    html = f"""
    <html>
    <head>
        <title>ReconX Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; background-color: #0d1117; color: #e6edf3; }}
            h1 {{ color: #00d26a; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ border: 1px solid #30363d; padding: 8px; text-align: left; }}
            th {{ background-color: #161b22; }}
            tr:nth-child(even) {{ background-color: #1c2128; }}
            .footer {{ margin-top: 30px; font-size: 12px; color: #8b949e; text-align: center; }}
        </style>
    </head>
    <body>
        <h1>ReconX Scan Report</h1>
        <p><strong>Generated:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
    """

    for host, info in data.items():
        html += f"<h2>Host: {host} ({info.get('state')})</h2>"
        for proto, ports in info.get("protocols", {}).items():
            html += f"<h3>Protocol: {proto}</h3>"
            html += "<table><tr><th>Port</th><th>State</th><th>Service</th><th>Product</th><th>Version</th></tr>"
            for port_data in ports:
                html += f"""
                <tr>
                    <td>{port_data.get('port')}</td>
                    <td>{port_data.get('state')}</td>
                    <td>{port_data.get('name')}</td>
                    <td>{port_data.get('product')}</td>
                    <td>{port_data.get('version')}</td>
                </tr>
                """
            html += "</table>"

    html += """
        <div class="footer">
            <p>Report generated by ReconX | Network Reconnaissance Toolkit</p>
        </div>
    </body>
    </html>
    """

    with open(output_file, "w") as f:
        f.write(html)

    print(f"[✓] HTML report created at {output_file}")

